name: "Jest-Cypress coverage"
description: "run jest and cypress coverage"
author: "Jabulani Mpofu"
inputs:
  accessToken:
    description: 'access token required to comment on a pr'
    required: false
    default: ${{ github.token }}
  prCoverageThreshold:
    description: 'JSON object of pr coverage threshold'
    required: false
    default: ''
  fullCoverageDiff:
    description: 'get the full coverage with diff or only the diff'
    required: false
    default: false
outputs:
  passed: # id of output
    description: "Did the coverage pass or fail"
runs:
  using: "node12"
  main: "dist/index.js"
