name: "Jest-Cypress coverage"
description: "run jest and cypress coverage"
author: "Jabulani Mpofu"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  accessToken:
    description: 'access token required to comment on a pr'
    required: false
    default: 'b9f36f9332684cd143a626d01fce537baf2d88d4'
  fullCoverageDiff:
    description: 'get the full coverage with diff or only the diff'
    required: false
    default: 'false'
  runCommand:
    description: 'custom command to get json-summary'
    default: 'npx jest --coverage --coverageReporters="json-summary" --coverageDirectory="./"'
    required: false
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "dist/index.js"
