name: "build"
on: # rebuild all pushes
  push:
    branches:
      - master
      - 'releases/*'
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all